import { useState, useEffect, useRef } from 'react';
import { motion } from 'motion/react';
import { Download, Share2, RefreshCw, Pen, Type } from 'lucide-react';
import { HandwritingStyle } from '../services/aiService';
import { renderHandwriting, exportToPDF } from '../services/handwritingService';
import { cn } from '../lib/utils';

interface GeneratorProps {
  style: HandwritingStyle;
}

export default function Generator({ style: initialStyle }: GeneratorProps) {
  const [text, setText] = useState("Dear Friend,\n\nThis is a sample of your digital handwriting generated by ScribeAI. Every stroke and curve is synthesized to replicate your unique style. I hope you find this useful for your notes and letters.\n\nWarm regards,\nScribeAI");
  const [style, setStyle] = useState(initialStyle);
  const [inkColor, setInkColor] = useState(initialStyle.inkColor || '#1a1a2e');
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isRendering, setIsRendering] = useState(false);

  useEffect(() => {
    const render = async () => {
      if (canvasRef.current) {
        setIsRendering(true);
        await renderHandwriting(canvasRef.current, {
          text,
          style,
          color: inkColor,
          pageSize: 'a4'
        });
        setIsRendering(false);
      }
    };
    render();
  }, [text, style, inkColor]);

  const handleDownload = () => {
    if (canvasRef.current) {
      exportToPDF(canvasRef.current, `Note_${Date.now()}.pdf`);
    }
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 max-w-7xl mx-auto">
      {/* Controls */}
      <div className="space-y-8">
        <div>
          <h2 className="text-3xl font-bold uppercase tracking-tighter mb-2">2. Compose Text</h2>
          <p className="text-[#666] italic">Write your note below. It will update in real-time on the right.</p>
        </div>

        <div className="relative">
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            className="w-full h-80 p-6 bg-white border border-[#141414] rounded-3xl outline-none focus:ring-2 ring-black/5 resize-none font-sans leading-relaxed text-lg"
            placeholder="Type your message here..."
          />
          <div className="absolute top-4 right-4 text-[#141414]/20">
            <Pen size={20} />
          </div>
        </div>

        <div className="p-6 bg-white border border-[#141414] rounded-3xl space-y-6">
          <h3 className="text-xs uppercase tracking-widest font-bold opacity-40">Style Fine-Tuning</h3>
          
          <div className="space-y-2">
            <p className="text-xs font-mono">Ink Color</p>
            <div className="flex gap-2">
              <input 
                type="color" 
                value={inkColor} 
                onChange={(e) => setInkColor(e.target.value)}
                className="w-10 h-10 rounded-full cursor-pointer border border-black/10 overflow-hidden"
              />
              <input 
                type="text" 
                value={inkColor}
                onChange={(e) => setInkColor(e.target.value)}
                className="flex-1 px-3 py-2 border rounded-lg font-mono text-xs uppercase"
              />
            </div>
          </div>

          <StyleSlider 
            label="Slant" 
            value={style.slant} 
            min={-20} max={20} 
            onChange={(val) => setStyle(s => ({...s, slant: val}))} 
          />
          <StyleSlider 
            label="Spacing" 
            value={style.spacing} 
            min={0.8} max={2.0} 
            step={0.1}
            onChange={(val) => setStyle(s => ({...s, spacing: val}))} 
          />
          <StyleSlider 
            label="Stroke Weight" 
            value={style.strokeWeight} 
            min={1} max={3} 
            step={0.1}
            onChange={(val) => setStyle(s => ({...s, strokeWeight: val}))} 
          />
          <StyleSlider 
            label="Jitter (Randomness)" 
            value={style.jitter} 
            min={0} max={5} 
            onChange={(val) => setStyle(s => ({...s, jitter: val}))} 
          />
        </div>

        <div className="flex gap-4">
          <button
            onClick={handleDownload}
            className="flex-1 py-4 bg-[#141414] text-[#E4E3E0] rounded-full font-medium hover:bg-[#333] transition-colors flex items-center justify-center gap-2"
          >
            Export to PDF <Download size={18} />
          </button>
          <button
            className="px-6 py-4 border border-[#141414] rounded-full hover:bg-[#d4d3d0] transition-colors"
          >
            <Share2 size={18} />
          </button>
        </div>
      </div>

      {/* Preview */}
      <div className="relative">
        <div className="sticky top-8">
          <div className="mb-4 flex items-center justify-between">
            <h2 className="text-xs uppercase tracking-widest font-bold opacity-40">Live Preview</h2>
            {isRendering && <RefreshCw className="animate-spin text-black/20" size={16} />}
          </div>
          
          <div className="bg-[#141414] p-4 rounded-[40px] shadow-2xl">
            <div className="bg-white aspect-[1/1.414] rounded-[32px] overflow-hidden shadow-inner">
              <canvas
                ref={canvasRef}
                width={800}
                height={1131} // A4 aspect ratio
                className="w-full h-full object-contain"
              />
            </div>
          </div>

          <div className="mt-8 space-y-4">
            <div className="flex items-center gap-2 mb-4">
              <div className="h-[1px] flex-1 bg-[#141414]/10" />
              <span className="text-[10px] uppercase font-bold tracking-widest opacity-40 whitespace-nowrap">Extracted DNA</span>
              <div className="h-[1px] flex-1 bg-[#141414]/10" />
            </div>

            <div className="grid grid-cols-2 gap-4">
              <DNACard label="Base Font" value={style.fontFamily.split(',')[0].replace(/'/g, '')} />
              <DNACard label="Primary Slant" value={`${style.slant}°`} />
              <DNACard label="Inter-letter" value={`${style.spacing}x`} />
              <DNACard label="Stroke Type" value={style.strokeWeight > 2 ? 'Heavy' : style.strokeWeight > 1.5 ? 'Medium' : 'Fine'} />
            </div>

            <div className="p-4 bg-white/50 border border-[#141414]/10 rounded-2xl flex items-center justify-between">
              <div>
                <p className="text-[10px] uppercase opacity-40 mb-1">Status</p>
                <p className="font-mono text-xs">{isRendering ? 'SYNTHESIZING STROKES...' : 'READY FOR EXPORT'}</p>
              </div>
              <div className={cn(
                "w-3 h-3 rounded-full",
                isRendering ? "bg-orange-500 animate-pulse" : "bg-green-500"
              )} />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function DNACard({ label, value }: { label: string, value: string | number }) {
  return (
    <div className="p-4 bg-white border border-[#141414]/5 rounded-2xl">
      <p className="text-[10px] uppercase opacity-40 mb-1">{label}</p>
      <p className="font-mono text-xs font-bold">{value}</p>
    </div>
  );
}

function StyleSlider({ label, value, min, max, step = 1, onChange }: { label: string, value: number, min: number, max: number, step?: number, onChange: (val: number) => void }) {
  return (
    <div className="space-y-2">
      <div className="flex justify-between text-xs font-mono">
        <span>{label}</span>
        <span>{typeof value === 'number' ? value.toFixed(step < 1 ? 1 : 0) : value}</span>
      </div>
      <input
        type="range"
        min={min}
        max={max}
        step={step}
        value={value}
        onChange={(e) => onChange(parseFloat(e.target.value))}
        className="w-full h-1 bg-[#141414]/10 rounded-lg appearance-none cursor-pointer accent-[#141414]"
      />
    </div>
  );
}
